-- =====================================================================
--  POS + Inventory Management System — MySQL Schema (CLEAN INSTALL)
--  Target: MySQL 8.0+ (InnoDB, utf8mb4)
--
--  SAFE TO RUN TWICE. It creates anything that is missing and leaves
--  existing data alone. Your products and sales are never touched.
--
--  To wipe everything and start over, run reset.sql instead — that one
--  deletes, and it says so.
--
--  This file gives you a system ready to use, but with NO STOCK DATA:
--    - three roles
--    - three staff accounts (one admin, two cashiers)
--    - eight product categories to sort your shelves into
--  Products, sales and inventory history all start empty. You add your
--  own products in the app.
--
--  Import in MySQL Workbench:  File > Open SQL Script > Execute
--  Or:  mysql -u root -p < schema.sql
-- =====================================================================

CREATE DATABASE IF NOT EXISTS pos_system
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;
USE pos_system;

-- ---------------------------------------------------------------------
-- 1. roles
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS roles (
  id          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name        VARCHAR(30)  NOT NULL UNIQUE,   -- 'admin' | 'cashier' | 'customer'
  description VARCHAR(255) NULL,
  created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- 2. users
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id            INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  role_id       INT UNSIGNED NOT NULL,
  username      VARCHAR(50)  NOT NULL UNIQUE,
  email         VARCHAR(120) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,        -- bcrypt; never store plaintext
  full_name     VARCHAR(120) NOT NULL,
  phone         VARCHAR(30)  NULL,
  is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
  last_login_at DATETIME     NULL,
  created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  INDEX idx_users_role (role_id)
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- 3. categories
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS categories (
  id          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name        VARCHAR(80)  NOT NULL UNIQUE,
  description VARCHAR(255) NULL,
  is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- 4. products
--    image_url holds a path like /uploads/products/<file>.jpg written by
--    the upload endpoint, or an external https:// address. Relative paths
--    keep the database portable if the server's domain changes.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS products (
  id                  INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  category_id         INT UNSIGNED NULL,
  sku                 VARCHAR(50)  NOT NULL UNIQUE,      -- generated by the app (BEV-0001); staff never type it
  barcode             VARCHAR(64)  NULL UNIQUE,      -- EAN-13 / UPC; nullable for loose goods
  name                VARCHAR(150) NOT NULL,
  description         TEXT         NULL,
  image_url           VARCHAR(255) NULL,
  unit                VARCHAR(20)  NOT NULL DEFAULT 'pcs',   -- pcs, box, kg, pack
  cost_price          DECIMAL(10,2) NOT NULL DEFAULT 0.00,   -- what you paid
  selling_price       DECIMAL(10,2) NOT NULL,                -- what the customer pays
  stock_quantity      INT          NOT NULL DEFAULT 0,
  low_stock_threshold INT          NOT NULL DEFAULT 10,
  expiry_date         DATE         NULL,               -- leave empty for goods that do not expire
  expiry_warning_days INT          NOT NULL DEFAULT 14, -- start warning this many days before
  is_active           BOOLEAN      NOT NULL DEFAULT TRUE,    -- soft delete: never hard-delete a sold product
  created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT chk_products_price CHECK (selling_price >= 0 AND cost_price >= 0),
  CONSTRAINT chk_products_stock CHECK (stock_quantity >= 0),
  INDEX idx_products_category (category_id),
  INDEX idx_products_active (is_active),
  INDEX idx_products_expiry (expiry_date),
  FULLTEXT INDEX ft_products_search (name, description)   -- powers the cashier search box
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- 5. sales  (one row per completed checkout / receipt)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sales (
  id              INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  invoice_no      VARCHAR(30)  NOT NULL UNIQUE,   -- e.g. INV-20260825-00001
  user_id         INT UNSIGNED NOT NULL,          -- cashier who rang it up
  subtotal        DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  discount_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  tax_amount      DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  total_amount    DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  payment_method  ENUM('cash','card','qr') NOT NULL DEFAULT 'cash',
  amount_paid     DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  change_due      DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  status          ENUM('completed','voided','refunded') NOT NULL DEFAULT 'completed',
  note            VARCHAR(255) NULL,
  created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_sales_user FOREIGN KEY (user_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  INDEX idx_sales_user (user_id),
  INDEX idx_sales_created (created_at),          -- date-range report filter
  INDEX idx_sales_status (status)
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- 6. sale_items  (line items — price/name are SNAPSHOTS, not live lookups)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sale_items (
  id             INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  sale_id        INT UNSIGNED NOT NULL,
  product_id     INT UNSIGNED NULL,              -- NULL if product later purged
  product_name   VARCHAR(150) NOT NULL,          -- snapshot: receipt must stay readable
  sku            VARCHAR(50)  NOT NULL,          -- snapshot
  unit_price     DECIMAL(10,2) NOT NULL,         -- snapshot: price at time of sale
  quantity       INT          NOT NULL,
  line_discount  DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  line_total     DECIMAL(10,2) NOT NULL,         -- (unit_price * quantity) - line_discount
  CONSTRAINT fk_items_sale FOREIGN KEY (sale_id) REFERENCES sales(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_items_product FOREIGN KEY (product_id) REFERENCES products(id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT chk_items_qty CHECK (quantity > 0),
  INDEX idx_items_sale (sale_id),
  INDEX idx_items_product (product_id)           -- powers "top-selling products"
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- 7. inventory_logs  (append-only audit trail of every stock movement)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS inventory_logs (
  id              INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  product_id      INT UNSIGNED NOT NULL,
  user_id         INT UNSIGNED NULL,             -- who caused it (NULL = system)
  change_type     ENUM('initial','sale','restock','adjustment','return','void','expired') NOT NULL,
  quantity_change INT          NOT NULL,         -- negative for sales, positive for restock
  stock_before    INT          NOT NULL,
  stock_after     INT          NOT NULL,
  reference_id    INT UNSIGNED NULL,             -- sales.id when change_type = 'sale'
  note            VARCHAR(255) NULL,
  created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_logs_product FOREIGN KEY (product_id) REFERENCES products(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_logs_user FOREIGN KEY (user_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  INDEX idx_logs_product (product_id),
  INDEX idx_logs_created (created_at),
  INDEX idx_logs_type (change_type)
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- Convenience views for the admin dashboard
-- ---------------------------------------------------------------------
CREATE OR REPLACE VIEW v_low_stock AS
SELECT p.id, p.sku, p.name, c.name AS category,
       p.stock_quantity, p.low_stock_threshold
FROM products p
LEFT JOIN categories c ON c.id = p.category_id
WHERE p.is_active = TRUE
  AND p.stock_quantity <= p.low_stock_threshold;

-- Anything already expired, or close enough to warn about. DATEDIFF gives the
-- number of days from today to the expiry date: negative means already past.
CREATE OR REPLACE VIEW v_expiring AS
SELECT p.id, p.sku, p.name, c.name AS category,
       p.stock_quantity, p.unit, p.cost_price, p.expiry_date,
       DATEDIFF(p.expiry_date, CURDATE()) AS days_left,
       (p.stock_quantity * p.cost_price)  AS value_at_risk,
       CASE WHEN DATEDIFF(p.expiry_date, CURDATE()) < 0 THEN 'expired'
            ELSE 'expiring' END           AS expiry_status
FROM products p
LEFT JOIN categories c ON c.id = p.category_id
WHERE p.is_active = TRUE
  AND p.expiry_date IS NOT NULL
  AND p.stock_quantity > 0
  AND DATEDIFF(p.expiry_date, CURDATE()) <= p.expiry_warning_days;


-- =====================================================================
--  STARTING ROWS
--  Roles, staff accounts and categories. No products, no sales — you
--  enter your own stock through the app.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Roles
-- ---------------------------------------------------------------------
INSERT IGNORE INTO roles (name, description) VALUES
  ('admin',    'Full access: products, sales, reports, staff'),
  ('cashier',  'POS checkout, own sales history, read-only products'),
  ('customer', 'Public product browsing only');

-- ---------------------------------------------------------------------
-- Staff accounts
--
-- INSERT IGNORE means "skip any row that already exists". So running this
-- file again will not duplicate these accounts, and will not reset a
-- password you have already changed.
--
-- password_hash is a PLACEHOLDER until you run, from the backend folder:
--     npm run seed:passwords
-- which sets admin -> admin123 and both cashiers -> cashier123.
--
-- CHANGE THESE before anyone real uses the system. Add or remove staff
-- from the Staff screen in the app; you do not need to edit SQL again.
-- ---------------------------------------------------------------------
INSERT IGNORE INTO users (role_id, username, email, password_hash, full_name, phone) VALUES
  (1, 'admin',    'admin@store.local',    'REPLACE_ME_BCRYPT_HASH', 'Store Owner', NULL),
  (2, 'cashier1', 'cashier1@store.local', 'REPLACE_ME_BCRYPT_HASH', 'Cashier One', NULL),
  (2, 'cashier2', 'cashier2@store.local', 'REPLACE_ME_BCRYPT_HASH', 'Cashier Two', NULL);

-- ---------------------------------------------------------------------
-- Categories
--
-- A typical convenience-store layout. Rename, delete or add your own in
-- the app (Products > Categories). A category with no products yet can
-- be deleted freely.
-- ---------------------------------------------------------------------
INSERT IGNORE INTO categories (name, description) VALUES
  ('Beverages',     'Water, soft drinks, juice, energy drinks'),
  ('Snacks',        'Chips, biscuits, sweets, nuts'),
  ('Dairy & Eggs',  'Milk, yoghurt, cheese, eggs'),
  ('Instant Food',  'Noodles, canned goods, ready meals'),
  ('Bakery',        'Bread, buns, cakes'),
  ('Household',     'Soap, detergent, tissue, cleaning'),
  ('Personal Care', 'Shampoo, toothpaste, razors'),
  ('Tobacco & Misc','Cigarettes, lighters, phone top-ups'),
  ('Vegetable','Brocoli, f, j');

-- ---------------------------------------------------------------------
-- Sanity check — expect 3 roles, 3 users, 8 categories, 0 products.
-- ---------------------------------------------------------------------
-- SELECT (SELECT COUNT(*) FROM roles)      AS roles,
--        (SELECT COUNT(*) FROM users)      AS users,
--        (SELECT COUNT(*) FROM categories) AS categories,
--        (SELECT COUNT(*) FROM products)   AS products,
--        (SELECT COUNT(*) FROM sales)      AS sales;
-- SELECT * FROM v_expiring ORDER BY days_left;
