-- =====================================================================
--  POS + Inventory Management System — MySQL Schema (CLEAN INSTALL)
--  Target: MySQL 8.0+ (InnoDB, utf8mb4)
--
--  SAFE TO RUN TWICE. It creates anything that is missing and leaves
--  existing data alone. Your products and sales are never touched.
--
--  To wipe everything and start over, run reset.sql instead — that one
--  deletes, and it says so.
--
--  This file gives you a system ready to use, but with NO STOCK DATA:
--    - three roles
--    - three staff accounts (one admin, two cashiers)
--    - eight product categories to sort your shelves into
--    - three example suppliers
--  Products, sales and inventory history all start empty. You add your
--  own products in the app.
--
--  Import in MySQL Workbench:  File > Open SQL Script > Execute
--  Or:  mysql -u root -p < schema.sql
-- =====================================================================

CREATE DATABASE IF NOT EXISTS pos_system
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;
USE pos_system;

-- ---------------------------------------------------------------------
-- 1. roles
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS roles (
  id          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name        VARCHAR(30)  NOT NULL UNIQUE,   -- 'admin' | 'cashier' | 'customer'
  description VARCHAR(255) NULL,
  created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- 2. users
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id            INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  role_id       INT UNSIGNED NOT NULL,
  username      VARCHAR(50)  NOT NULL UNIQUE,
  email         VARCHAR(120) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,        -- bcrypt; never store plaintext
  full_name     VARCHAR(120) NOT NULL,
  phone         VARCHAR(30)  NULL,
  is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
  last_login_at DATETIME     NULL,
  created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  INDEX idx_users_role (role_id)
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- 3. categories
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS categories (
  id          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name        VARCHAR(80)  NOT NULL UNIQUE,
  description VARCHAR(255) NULL,
  is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- 4. products
--    image_url holds a path like /uploads/products/<file>.jpg written by
--    the upload endpoint, or an external https:// address. Relative paths
--    keep the database portable if the server's domain changes.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS products (
  id                  INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  category_id         INT UNSIGNED NULL,
  sku                 VARCHAR(50)  NOT NULL UNIQUE,      -- generated by the app (BEV-0001); staff never type it
  barcode             VARCHAR(64)  NULL UNIQUE,      -- EAN-13 / UPC; nullable for loose goods
  name                VARCHAR(150) NOT NULL,
  description         TEXT         NULL,
  image_url           VARCHAR(255) NULL,
  unit                VARCHAR(20)  NOT NULL DEFAULT 'pcs',   -- pcs, box, kg, pack
  cost_price          DECIMAL(10,2) NOT NULL DEFAULT 0.00,   -- what you paid
  selling_price       DECIMAL(10,2) NOT NULL,                -- what the customer pays
  stock_quantity      INT          NOT NULL DEFAULT 0,
  low_stock_threshold INT          NOT NULL DEFAULT 10,
  expiry_date         DATE         NULL,               -- leave empty for goods that do not expire
  expiry_warning_days INT          NOT NULL DEFAULT 14, -- start warning this many days before
  is_active           BOOLEAN      NOT NULL DEFAULT TRUE,    -- soft delete: never hard-delete a sold product
  created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT chk_products_price CHECK (selling_price >= 0 AND cost_price >= 0),
  CONSTRAINT chk_products_stock CHECK (stock_quantity >= 0),
  INDEX idx_products_category (category_id),
  INDEX idx_products_active (is_active),
  INDEX idx_products_expiry (expiry_date),
  FULLTEXT INDEX ft_products_search (name, description)   -- powers the cashier search box
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- 5. sales  (one row per completed checkout / receipt)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sales (
  id              INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  invoice_no      VARCHAR(30)  NOT NULL UNIQUE,   -- e.g. INV-20260825-00001
  user_id         INT UNSIGNED NOT NULL,          -- cashier who rang it up
  subtotal        DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  discount_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  tax_amount      DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  total_amount    DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  payment_method  ENUM('cash','card','qr') NOT NULL DEFAULT 'cash',
  amount_paid     DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  change_due      DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  status          ENUM('completed','voided','refunded') NOT NULL DEFAULT 'completed',
  note            VARCHAR(255) NULL,
  created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_sales_user FOREIGN KEY (user_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  INDEX idx_sales_user (user_id),
  INDEX idx_sales_created (created_at),          -- date-range report filter
  INDEX idx_sales_status (status)
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- 6. sale_items  (line items — price/name are SNAPSHOTS, not live lookups)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sale_items (
  id             INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  sale_id        INT UNSIGNED NOT NULL,
  product_id     INT UNSIGNED NULL,              -- NULL if product later purged
  product_name   VARCHAR(150) NOT NULL,          -- snapshot: receipt must stay readable
  sku            VARCHAR(50)  NOT NULL,          -- snapshot
  unit_price     DECIMAL(10,2) NOT NULL,         -- snapshot: price at time of sale
  quantity       INT          NOT NULL,
  line_discount  DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  line_total     DECIMAL(10,2) NOT NULL,         -- (unit_price * quantity) - line_discount
  CONSTRAINT fk_items_sale FOREIGN KEY (sale_id) REFERENCES sales(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_items_product FOREIGN KEY (product_id) REFERENCES products(id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT chk_items_qty CHECK (quantity > 0),
  INDEX idx_items_sale (sale_id),
  INDEX idx_items_product (product_id)           -- powers "top-selling products"
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- 7. inventory_logs  (append-only audit trail of every stock movement)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS inventory_logs (
  id              INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  product_id      INT UNSIGNED NOT NULL,
  user_id         INT UNSIGNED NULL,             -- who caused it (NULL = system)
  change_type     ENUM('initial','sale','restock','adjustment','return','void','expired','received') NOT NULL,
  quantity_change INT          NOT NULL,         -- negative for sales, positive for restock
  stock_before    INT          NOT NULL,
  stock_after     INT          NOT NULL,
  reference_id    INT UNSIGNED NULL,             -- sales.id for 'sale', purchase_orders.id for 'received'
  batch_id        INT UNSIGNED NULL,             -- which batch the stock came from or went to
  note            VARCHAR(255) NULL,
  created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_logs_product FOREIGN KEY (product_id) REFERENCES products(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_logs_user FOREIGN KEY (user_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  INDEX idx_logs_product (product_id),
  INDEX idx_logs_created (created_at),
  INDEX idx_logs_type (change_type)
) ENGINE=InnoDB;


-- ---------------------------------------------------------------------
-- 8. suppliers
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS suppliers (
  id             INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name           VARCHAR(120) NOT NULL UNIQUE,
  contact_person VARCHAR(120) NULL,
  phone          VARCHAR(30)  NULL,
  email          VARCHAR(120) NULL,
  address        VARCHAR(255) NULL,
  note           VARCHAR(255) NULL,
  is_active      BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- 9. purchase_orders  (stock you have ordered but not yet received)
--
--    Mirrors the sales tables: a header row plus line items. The status
--    walks forward: draft -> ordered -> partial -> received.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS purchase_orders (
  id            INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  po_number     VARCHAR(30)  NOT NULL UNIQUE,   -- PO-20260825-00007
  supplier_id   INT UNSIGNED NULL,
  user_id       INT UNSIGNED NOT NULL,          -- who raised it
  status        ENUM('draft','ordered','partial','received','cancelled') NOT NULL DEFAULT 'draft',
  order_date    DATE         NULL,              -- when it was sent to the supplier
  expected_date DATE         NULL,              -- when they said it would arrive
  received_date DATE         NULL,              -- when the last item landed
  total_cost    DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  note          VARCHAR(255) NULL,
  created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_po_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_po_user FOREIGN KEY (user_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  INDEX idx_po_status (status),
  INDEX idx_po_supplier (supplier_id),
  INDEX idx_po_expected (expected_date)
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- 10. purchase_order_items
--     quantity_received climbs as deliveries arrive, so a part-delivered
--     order shows exactly what is still outstanding.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS purchase_order_items (
  id                INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  purchase_order_id INT UNSIGNED NOT NULL,
  product_id        INT UNSIGNED NULL,
  product_name      VARCHAR(150) NOT NULL,      -- snapshot, as with sale_items
  quantity_ordered  INT          NOT NULL,
  quantity_received INT          NOT NULL DEFAULT 0,
  unit_cost         DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  expiry_date       DATE         NULL,          -- what you expect to be delivered
  line_total        DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  CONSTRAINT fk_poi_order FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_poi_product FOREIGN KEY (product_id) REFERENCES products(id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT chk_poi_qty CHECK (quantity_ordered > 0 AND quantity_received >= 0),
  INDEX idx_poi_order (purchase_order_id),
  INDEX idx_poi_product (product_id)
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- 11. product_batches  — this is what separates old stock from new
--
--     Every delivery of a product becomes its own row, with its own cost
--     price and its own expiry date. Two deliveries of milk with
--     different dates are two batches, not one muddled number.
--
--     quantity_remaining counts down as the batch is sold. A batch at
--     zero stays for the history; it is simply skipped when selling.
--
--     products.stock_quantity is kept as the SUM of the remaining
--     quantities. Keeping that running total means the till and the
--     product list stay fast, and every screen written before batches
--     existed still works.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS product_batches (
  id                INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  product_id        INT UNSIGNED NOT NULL,
  batch_no          VARCHAR(40)  NULL,          -- supplier's lot number, if they give one
  purchase_order_id INT UNSIGNED NULL,          -- which delivery it came from
  quantity_received INT          NOT NULL,
  quantity_remaining INT         NOT NULL,
  cost_price        DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  expiry_date       DATE         NULL,
  received_at       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  note              VARCHAR(255) NULL,
  CONSTRAINT fk_batch_product FOREIGN KEY (product_id) REFERENCES products(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_batch_po FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT chk_batch_qty CHECK (quantity_received > 0 AND quantity_remaining >= 0),
  -- The order the till sells in: earliest expiry first, then oldest delivery.
  INDEX idx_batch_pick (product_id, expiry_date, received_at),
  INDEX idx_batch_expiry (expiry_date)
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- Convenience views for the admin dashboard
-- ---------------------------------------------------------------------
CREATE OR REPLACE VIEW v_low_stock AS
SELECT p.id, p.sku, p.name, c.name AS category,
       p.stock_quantity, p.low_stock_threshold
FROM products p
LEFT JOIN categories c ON c.id = p.category_id
WHERE p.is_active = TRUE
  AND p.stock_quantity <= p.low_stock_threshold;

-- Anything already expired, or close enough to warn about. DATEDIFF gives the
-- number of days from today to the expiry date: negative means already past.
-- One row per BATCH, not per product: an old batch can be expiring while a
-- fresh one of the same product is fine, and you need to see both.
CREATE OR REPLACE VIEW v_expiring AS
SELECT b.id AS batch_id, p.id, p.sku, p.name, c.name AS category,
       b.batch_no, b.quantity_remaining AS stock_quantity, p.unit,
       b.cost_price, b.expiry_date, b.received_at,
       DATEDIFF(b.expiry_date, CURDATE())        AS days_left,
       (b.quantity_remaining * b.cost_price)     AS value_at_risk,
       CASE WHEN DATEDIFF(b.expiry_date, CURDATE()) < 0 THEN 'expired'
            ELSE 'expiring' END                  AS expiry_status
FROM product_batches b
JOIN products p ON p.id = b.product_id
LEFT JOIN categories c ON c.id = p.category_id
WHERE p.is_active = TRUE
  AND b.expiry_date IS NOT NULL
  AND b.quantity_remaining > 0
  AND DATEDIFF(b.expiry_date, CURDATE()) <= p.expiry_warning_days;

-- What is on order and still outstanding.
CREATE OR REPLACE VIEW v_on_order AS
SELECT i.product_id, p.name AS product_name, p.sku,
       SUM(i.quantity_ordered - i.quantity_received) AS quantity_on_order,
       MIN(o.expected_date)                          AS next_expected
FROM purchase_order_items i
JOIN purchase_orders o ON o.id = i.purchase_order_id
JOIN products p ON p.id = i.product_id
WHERE o.status IN ('ordered', 'partial')
  AND i.quantity_received < i.quantity_ordered
GROUP BY i.product_id, p.name, p.sku;


-- =====================================================================
--  STARTING ROWS
--  Roles, staff accounts and categories. No products, no sales — you
--  enter your own stock through the app.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Roles
-- ---------------------------------------------------------------------
INSERT IGNORE INTO roles (name, description) VALUES
  ('admin',    'Full access: products, sales, reports, staff'),
  ('cashier',  'POS checkout, own sales history, read-only products'),
  ('customer', 'Public product browsing only');

-- ---------------------------------------------------------------------
-- Staff accounts
--
-- INSERT IGNORE means "skip any row that already exists". So running this
-- file again will not duplicate these accounts, and will not reset a
-- password you have already changed.
--
-- password_hash is a PLACEHOLDER until you run, from the backend folder:
--     npm run seed:passwords
-- which sets admin -> admin123 and both cashiers -> cashier123.
--
-- CHANGE THESE before anyone real uses the system. Add or remove staff
-- from the Staff screen in the app; you do not need to edit SQL again.
-- ---------------------------------------------------------------------
INSERT IGNORE INTO users (role_id, username, email, password_hash, full_name, phone) VALUES
  (1, 'admin',    'admin@store.local',    'REPLACE_ME_BCRYPT_HASH', 'Store Owner', NULL),
  (2, 'cashier1', 'cashier1@store.local', 'REPLACE_ME_BCRYPT_HASH', 'Cashier One', NULL),
  (2, 'cashier2', 'cashier2@store.local', 'REPLACE_ME_BCRYPT_HASH', 'Cashier Two', NULL);

-- ---------------------------------------------------------------------
-- Categories
--
-- A typical convenience-store layout. Rename, delete or add your own in
-- the app (Products > Categories). A category with no products yet can
-- be deleted freely.
-- ---------------------------------------------------------------------
INSERT IGNORE INTO categories (name, description) VALUES
  ('Beverages',     'Water, soft drinks, juice, energy drinks'),
  ('Snacks',        'Chips, biscuits, sweets, nuts'),
  ('Dairy & Eggs',  'Milk, yoghurt, cheese, eggs'),
  ('Instant Food',  'Noodles, canned goods, ready meals'),
  ('Bakery',        'Bread, buns, cakes'),
  ('Household',     'Soap, detergent, tissue, cleaning'),
  ('Personal Care', 'Shampoo, toothpaste, razors'),
  ('Tobacco & Misc','Cigarettes, lighters, phone top-ups');

-- ---------------------------------------------------------------------
-- Suppliers — rename or delete these; add your own from the app.
-- ---------------------------------------------------------------------
INSERT IGNORE INTO suppliers (name, contact_person, phone) VALUES
  ('General Wholesaler', NULL, NULL),
  ('Local Dairy',        NULL, NULL),
  ('Drinks Distributor', NULL, NULL);

-- ---------------------------------------------------------------------
-- Sanity check — expect 3 roles, 3 users, 8 categories, 0 products.
-- ---------------------------------------------------------------------
-- SELECT (SELECT COUNT(*) FROM roles)      AS roles,
--        (SELECT COUNT(*) FROM users)      AS users,
--        (SELECT COUNT(*) FROM categories) AS categories,
--        (SELECT COUNT(*) FROM products)   AS products,
--        (SELECT COUNT(*) FROM sales)      AS sales;
-- SELECT * FROM v_expiring ORDER BY days_left;
